"""empty message

Revision ID: 5919a14c553e
Revises: fee7055e55ec
Create Date: 2021-04-22 07:48:21.944818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5919a14c553e'
down_revision = 'fee7055e55ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cars', 'model',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cars', 'model',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=4),
               existing_nullable=True)
    # ### end Alembic commands ###
