"""empty message

<<<<<<< HEAD:migrations/versions/ef8944115aa6_.py
Revision ID: ef8944115aa6
Revises: 
Create Date: 2021-04-24 21:18:25.905890
=======
Revision ID: d91afee530e2
Revises: 
Create Date: 2021-04-24 22:11:44.172286
>>>>>>> 81e9a119105b214eb9cd9eba4b226db1eaaf7cde:migrations/versions/d91afee530e2_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:migrations/versions/ef8944115aa6_.py
revision = 'ef8944115aa6'
=======
revision = 'd91afee530e2'
>>>>>>> 81e9a119105b214eb9cd9eba4b226db1eaaf7cde:migrations/versions/d91afee530e2_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('colour', sa.String(length=50), nullable=True),
    sa.Column('year', sa.String(length=10), nullable=True),
    sa.Column('transmission', sa.String(length=100), nullable=True),
    sa.Column('car_type', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('photo', sa.String(length=100), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favourites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=300), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=250), nullable=True),
    sa.Column('biography', sa.String(length=2500), nullable=True),
    sa.Column('photo', sa.String(length=100), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('favourites')
    op.drop_table('cars')
    # ### end Alembic commands ###
