"""empty message

Revision ID: fee7055e55ec
Revises: 18f3ffcc6e52
Create Date: 2021-04-22 06:25:00.383758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fee7055e55ec'
down_revision = '18f3ffcc6e52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('year', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'year')
    # ### end Alembic commands ###
